umbraco-community/awesome-umbraco

- README.md
Add some more packages, denote paid for options.
> More awesome

- README.md
Disclaimer: SEO Metadata is my project.
> Added uSync, Zbu Models Builder, SEO Metadata

- README.md
Added [Form Editor](https://github.com/kjac/FormEditor) to the list of backoffice extensions.
> Add Form Editor to the list

- README.md
This adds the **Switcher** property editor to the list of Backoffice extension
> Add Switcher

- README.md
I hope it's okay to add ones own packages ;)
I can also see that most of the referenced packages link to the package page at Our Umbraco. Our packages tend to have more information available on the GitHub project page, so I've linked to them instead.
> Added a few of our own packages

- README.md
Added multi url picker, doc type grid editor, UnVersion and full text search
Full Text Search was a quick and eassy way we figured out to get the search on a very up-against-time website with grid working.
> Added few packages and website utilities

- README.md
> Updated links to Our Umbraco to HTTPS

- README.md
Added subcategories for...
* Form Builders
* Grid Editors
* Property Editors
* SEO Tools
> Added subcategories the Backoffice Extensions category

- README.md
> Added in Terratype

- README.md
One of my favorite packages right now! Resolving issue #25.
> Added Styled Textbox

- README.md
Added 2 of my packages than may be usefull for others
> Added nexu an OEmbed Picker property editor

- README.md
https://our.umbraco.org/projects/backoffice-extensions/umbraco-latch/
https://umbracolatch.readme.io/
> Add Umbraco Latch

- README.md
> Added uEditorNotes

- CONTRIBUTING.md
- README.md
Added links for two packages that help with the editor experience: 
* v7 Dialog Expander
* Inline HTML Help Label
Thanks!
-Jason
>  Added "v7 Dialog Expander" and "Inline HTML Help"

- README.md
> Addition of Courier and Deploy contrib repos

- README.md
> Add the Health checks package

- README.md
Update around courier and deploy
> Update around courier and deploy

- UMBRACO-V7.md
Since opening issue #56 for Hacktoberfest (to review the list for Umbraco v8), I've archived off the Umbraco v7 list - for prosperity.
> Move Umbraco v7 list to its own file

- README.md
Tried to go around all packages listed and see what the compatibility is and remove any that do not support Umbraco 8.
Also added Vendr and Matryoshka as I feel like they play an important role in the Umbraco ecosystem. But I can always remove them if they disagree
> Updated list for Umbraco 8

- README.md
I have added an AWESOME podcast to the community content list
> Awesome podcast added and other small changes

- README.md
Thought I'd link to v7 version incase folks are looking for that :)
> Adding a link to v7  & 24days link

- README.md
Added the following packages:
SimpleRedirects - https://our.umbraco.com/packages/backoffice-extensions/simpleredirects/
InboundLinkErrors - https://our.umbraco.com/packages/website-utilities/inbound-link-errors/
Newsletter Studio - https://our.umbraco.com/packages/backoffice-extensions/newsletter-studio-the-email-studio/ (is licensed)
Diplo God Mode - https://our.umbraco.com/packages/developer-tools/diplo-god-mode/
Full Text Search - https://our.umbraco.com/packages/website-utilities/full-text-search-for-umbraco/
Backoffice Themes - https://our.umbraco.com/packages/backoffice-extensions/backoffice-themes/
Preflight - https://our.umbraco.com/packages/backoffice-extensions/preflight-content-health-checks-for-umbraco-8/
OpenOrClosed - …
> Added new v9 packages

- README.md
- UMBRACO-V8.md
Add 301 Urltracker, Datefolders, Alphabetfolders and Key value list
> Add packages

- README.md
- UMBRACO-V7.md
- UMBRACO-V9.md
- Moved V9 to its own list
- Added v10 list as default list
- Added new badges for the v10 navigation
- Went through all the packages, removed non v10 packages and added 3 packages (Konstrukt, SeoToolkit, SEO checker)
> Added list for v10
